services:
  mkdocs:
    image: squidfunk/mkdocs-material
    container_name: mkdocs-material
    ports:
      - "20888:8000"
    restart: unless-stopped
    volumes:
      - .:/docs
#    command: sh -c "mkdocs-material serve -a 0.0.0.0:20888"

