site_name: My Documentations

theme:
  name: mkdocs

plugins:
  - search

extra_css:
  - extra/custom.css

extra_javascript:
  - extra/shortcut.js

markdown_extensions:
  - toc:
      baselevel: "3"
      toc_depth: "3"
